title: Mangat Rai site
description: This is a sample website hosted on GitHub Pages.
theme: jekyll-theme-slate # Optional: You can choose another theme
url: "https://mangatRai10.github.io" # Replace with your GitHub username
baseurl: "/rEADME" # If you want to host in a sub-directory
